FROM node:24 

WORKDIR /app
COPY package.json .
RUN npm install
COPY . . 
EXPOSE 8000
VOLUME ["/app/node_modules"]
RUN npx prisma db push
RUN npx prisma migrate
RUN npx prisma generate
RUN npm run build
CMD ["npm","start"]